repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-shebang-scripts-are-executable

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black

-   repo: https://github.com/python-poetry/poetry
    rev: '1.4.0'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "--output", "requirements.txt", "--without-hashes"]

-   repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run pytest -v
        language: system
        pass_filenames: false
        always_run: true
