---
name: ✨ Feature Request
description: Propose a new j2escape feature or enhancement
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: ""
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature or enhancement you'd like to see.
      placeholder: |
        I would like to see a new feature that would allow me to ...
    validations:
      required: true
  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe the use cases
