name: pre-commit

on:
  pull_request:
  push:
    branches: ["main", "develop"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    # install poetry
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - uses: Gr1N/setup-poetry@v8
    - run: poetry --version

    # install pre-commit
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
